create table hi ( username varchar2(100), age number(3) );
insert into hi values ('까꿍', 31);
desc hi;
select * from hi;
delete table hi;
purge recyclebin;
select tname from tab;
select * from tab;
drop view emp details view;
truncate table mlist;
select * from mlist;
create sequence num_mlist;
select num_mlist.nextval from dual;
drop sequence num_mlist;
create sequence mlist_sqc;
desc mlist;
insert into mlist (reg, userid, psw, title, cntnt, wt, viewcnt) values (mlist_sqc.nextval, 'eee','fff', '이건', '마지막으로 넣자','2017-3-8','3');
select * from mlist where title like '%롱%';
select * from mlist where userid = 'aaa' or userid = 'bbb';
select * from mlist order by userid desc, viewcnt desc;
select * from mlist where viewcnt > 50 and reg > 2 and reg < 5 order by reg desc;
select * from mlist where wt >= '2018/11/01';
select * from mlist where 2*reg < viewcnt;
commit;
insert into mlist (reg, userid, psw, title, cntnt, wt, viewcnt) values(mlist_sqc.nextval, 'qvo', 'qqo', 'title', '내용인데 contents', '2016-2-18', '184');
select * from mlist where viewcnt >=20 and reg >= 10 and reg <20 order by reg desc;
select * from mlist where viewcnt >= 20 and reg between 10 and 20 order by reg desc;
desc mlist;
insert into mlist (reg, userid, psw, title, cntnt, wt, viewcnt) values(mlist_sqc.nextval, 'id', 'pswd', '제목 할 거 없네', '영자님 위에 글 삭제좀', '', '98');
select to_char(wt, 'yyyy/mm/dd hh:mi:ss') from mlist;
select to_char(wt, 'mm/dd day hh24:mi') from mlist;

select * from mlist where wt >= '1999/11/01' and wt < '2018/12/01';
select wt from mlist where to_char(wt, 'yyyymm')='201703';
select reg, viewcnt + 2, title || 'abc' from mlist;
insert into mlist (reg, userid, psw, title, cntnt, wt, viewcnt) values(mlist_sqc.nextval, '아디',  '번', '또 제목 아무거나', '이번에도 현재시각', sysdate, '132');

select wt, sysdate - wt from mlist;

select to_char(wt, 'mmdd') from mlist;
select sysdate - wt between 0 and 3 from mlist;
select wt where to_char(wt, 'yyyymmdd') - to_chat(sysdat, 'yyyymmdd') <= 3 and viewcnt >= 20 from mlist;
select wt from mlist where sysdate - wt < 3;
select wt from mlist where to_char(wt,'mm') = to_char(sysdate,'mm');
select wt from mlist where to_char(sysdate, 'yyyy') - to_char(wt, 'yyyy') <= 3;
select wt from mlist where to_char(sysdate, 'dd') - to_char(wt, 'dd') <=14;
select wt from mlist where to_char(wt,'mm') between 1 and 3;
commit;
desc mlist;
insert into mlist values(mlist_sqc.nextval, 'xxx', 'yyy', '다양한', '내용과 날짜', '2017/7/13','72');
select distinct userid from mlist order by userid;
select userid upper(userid), lower(userid), length(userid), substr(userid, 1, 3) from board;
select userid from mlist where length(userid) >= 3 and substr(userid, 1, 1) = 'a'; 
select wt, months_between ( sysdate, wt)  from mlist;
select userid, wt, add_months(wt, 3) from mlist;
select to_number( to_char(sysdate, 'MM') ) - to_number( to_char(wt, 'MM') )from mlist;
select sysdate, wt, to_char(wt, 'mm'), to_number( to_char(sysdate, 'MM') ) - to_number( to_char(wt, 'MM') ) from mlist where to_number( to_char(sysdate, 'MM') ) - to_number( to_char(wt, 'MM') ) < 5;
desc address;
drop table address;
create table address(name varchar2(20) not null, phone varchar2(20), age number(3), birth date default sysdate);
insert into address (name, phone, birth, age) values ('노수', '010-3983-1994', '1992-10-23','27');
insert into address (name, phone, birth, age) values ('서상', '010-8462-8545', '1998-8-21','23');
insert into address (name, phone, birth, age) values ('양상', '010-6617-1782', '1989-9-17','29');
select name from address where name like '%상';
insert into address (name, phone, birth, age) values ('이로', '010-8117-8242', '1985-5-7','29');
select name, birth,birth- sysdate from address;
insert into address (name, phone, birth, age) values ('노가', '010-8921-9641', '1996-3-25','23');
insert into address and intest (name, phone, birth, age) values ('용씨', '010-8153-8145', '2001-9-15','18');
insert into address (name, phone, birth, age) values ('안녕', '010-5784-1525', '1988-11-25','31');
select name, birth from address where to_char(birth, 'dd') -  to_char(sysdate, 'dd') between -7 and 7;
select name, birth from address where to_char(birth, 'mmdd') between 
commit;
desc address;
update address set age = 32, phone = '010-2134-3253' where name like '이로';
update address set age = age + 2 where name like '양상' and age = 28;
create table intest (name varchar2(20) not null, phone varchar2(20), age number(3), birth date default sysdate);
insert into address (name, phone, birth, age) and intest (name, phone, birth, age) values ('용씨', '010-8153-8145', '2001-9-15','18');
desc intest;
delete from address where name like '홍길동';
update mlist set title = '수정', cntnt = '수정 됨' where reg = 21;
update mlist set viewcnt = viewcnt + 1 where reg = 22;
delete from mlist where userid like 'id';
update mlist set wt = wt + 1 where reg = 21;
update mlist as board;
select * from mlist;
select * from address;
update address set phone = null where name like '양상' and age = 30;
select * from address where phone is null;
select count(age) from address;
select  count(reg) from mlist where to_char(wt, 'mm') = '11';
select max(age) from address;
select userid from mlist where reg = ( select max(reg) from mlist) ;
select userid, title from mlist where reg = ( select max(reg) from mlist);
select rownum,reg, userid, title, from (select * from mlist order by reg desc) where rownum <= 5;
--평균 조회수보다 높은 글을 쓴 사람들의 아이디 목록
select userid,title from mlist where viewcnt >= (select avg(viewcnt) from mlist);
select userid, avg(viewcnt) from mlist group by userid order by userid;
commit;

select avg(salary) m from employees
where salary > 3000 having m > 5000 group by department_id;